# Generated by Django 3.1.2 on 2020-10-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avater',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
